spring.application.name=msvc-items
server.port=8002

##Configuramos este microservicio como cliente de eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

##Base endopoint (configuracion propia nuestra)
config.base-url.endpoint.msvc-products=http://msvc-products